# Generated by Django 5.1.7 on 2025-03-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duplicatearticle',
            name='authors',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='selectedarticle',
            name='authors',
            field=models.TextField(),
        ),
    ]
